apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: prediction
  name: prediction
spec: 
  replicas: 2
  selector:
    matchLabels:
      service: prediction
  template:
    metadata:
      labels:
        service: prediction
        api: external
    spec:
      containers: 
      - name: house-cost-prediction
        image: 

services:
  web:
    image: dockersamples/k8s-wordsmith-web
    ports:
     - "80:80"

  words:
    image: dockersamples/k8s-wordsmith-api
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M